package payments.qrrefund.domain.error;

public enum RefundRejectionCode {
    INVALID_REQUEST,
    INVALID_REASON_CODE,
    ORIGINAL_PAYMENT_NOT_FOUND,
    MERCHANT_NOT_AUTHORIZED,
    PAYMENT_NOT_COMPLETED,
    REFUND_WINDOW_EXPIRED,
    MERCHANT_SUSPENDED,
    DUPLICATE_REFUND,
    IDEMPOTENCY_CONFLICT,
    IDEMPOTENCY_STATE_NOT_FOUND
}
