package payments.khqrreversal.domain.error;

public enum ReversalRejectionCode {
    INVALID_REQUEST,
    UNAUTHORIZED_MAKER,
    ORIGINAL_PAYMENT_NOT_FOUND,
    PAYMENT_NOT_COMPLETED,
    SETTLEMENT_CUTOFF_NOT_ELIGIBLE,
    PARTIAL_AMOUNT_NOT_SUPPORTED,
    INVALID_REASON_CODE,
    MISSING_IDEMPOTENCY_KEY,
    IDEMPOTENCY_CONFLICT,
    IDEMPOTENCY_STATE_NOT_FOUND,
    DUPLICATE_REVERSAL
}
